#ifndef QTCACHENAMESPACECONFIG_H
#define QTCACHENAMESPACECONFIG_H

#define QTCACHENAMESPACE QtC
#define QTCACHENAMESPACEBEGIN namespace QTCACHENAMESPACE {
#define QTCACHENAMESPACEEND }
#define QTCACHENAMESPACEUSE using namespace QTCACHENAMESPACE;

#endif // QTCACHENAMESPACECONFIG_H

