#ifndef QTCACHEGITPLUGIN_GLOBAL_H
#define QTCACHEGITPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTCACHEGITPLUGIN_LIBRARY)
#  define QTCACHEGITPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTCACHEGITPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCACHEGITPLUGIN_GLOBAL_H
