#ifndef QTCACHEPLUGINSAMPLE_GLOBAL_H
#define QTCACHEPLUGINSAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTCACHEPLUGINSAMPLE_LIBRARY)
#  define QTCACHEPLUGINSAMPLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTCACHEPLUGINSAMPLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCACHEPLUGINSAMPLE_GLOBAL_H
