/****************************************************************************
**
** Metadata for VISM generated by dumpcpp v5.5.1 using
** dumpcpp.exe -n VISM c:\Program Files (x86)\Common Files\InterSystems\Cache\VISM.ocx -o D:\src\QtCache\Intersystems\vismocx
** from the type library c:\Program Files (x86)\Common Files\InterSystems\Cache\VISM.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_VISM_NOINLINES
#include "vismocx.h"

using namespace VISM;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[115];
    char stringdata0[1093];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 12, 0),
QT_MOC_LITERAL(1, 13, 9, 0),
QT_MOC_LITERAL(2, 23, 0, 0),
QT_MOC_LITERAL(3, 24, 4, 0),
QT_MOC_LITERAL(4, 29, 6, 0),
QT_MOC_LITERAL(5, 36, 4, 0),
QT_MOC_LITERAL(6, 41, 4, 0),
QT_MOC_LITERAL(7, 46, 15, 0),
QT_MOC_LITERAL(8, 62, 4, 0),
QT_MOC_LITERAL(9, 67, 6, 0),
QT_MOC_LITERAL(10, 74, 4, 0),
QT_MOC_LITERAL(11, 79, 4, 0),
QT_MOC_LITERAL(12, 84, 8, 0),
QT_MOC_LITERAL(13, 93, 7, 0),
QT_MOC_LITERAL(14, 101, 16, 0),
QT_MOC_LITERAL(15, 118, 3, 0),
QT_MOC_LITERAL(16, 122, 16, 0),
QT_MOC_LITERAL(17, 139, 7, 0),
QT_MOC_LITERAL(18, 147, 4, 0),
QT_MOC_LITERAL(19, 152, 10, 0),
QT_MOC_LITERAL(20, 163, 9, 0),
QT_MOC_LITERAL(21, 173, 15, 0),
QT_MOC_LITERAL(22, 189, 8, 0),
QT_MOC_LITERAL(23, 198, 15, 0),
QT_MOC_LITERAL(24, 214, 6, 0),
QT_MOC_LITERAL(25, 221, 12, 0),
QT_MOC_LITERAL(26, 234, 9, 0),
QT_MOC_LITERAL(27, 244, 7, 0),
QT_MOC_LITERAL(28, 252, 10, 0),
QT_MOC_LITERAL(29, 263, 7, 0),
QT_MOC_LITERAL(30, 271, 18, 0),
QT_MOC_LITERAL(31, 290, 15, 0),
QT_MOC_LITERAL(32, 306, 17, 0),
QT_MOC_LITERAL(33, 324, 14, 0),
QT_MOC_LITERAL(34, 339, 14, 0),
QT_MOC_LITERAL(35, 354, 11, 0),
QT_MOC_LITERAL(36, 366, 8, 0),
QT_MOC_LITERAL(37, 375, 5, 0),
QT_MOC_LITERAL(38, 381, 12, 0),
QT_MOC_LITERAL(39, 394, 9, 0),
QT_MOC_LITERAL(40, 404, 12, 0),
QT_MOC_LITERAL(41, 417, 9, 0),
QT_MOC_LITERAL(42, 427, 11, 0),
QT_MOC_LITERAL(43, 439, 8, 0),
QT_MOC_LITERAL(44, 448, 7, 0),
QT_MOC_LITERAL(45, 456, 4, 0),
QT_MOC_LITERAL(46, 461, 11, 0),
QT_MOC_LITERAL(47, 473, 8, 0),
QT_MOC_LITERAL(48, 482, 10, 0),
QT_MOC_LITERAL(49, 493, 7, 0),
QT_MOC_LITERAL(50, 501, 11, 0),
QT_MOC_LITERAL(51, 513, 8, 0),
QT_MOC_LITERAL(52, 522, 20, 0),
QT_MOC_LITERAL(53, 543, 17, 0),
QT_MOC_LITERAL(54, 561, 19, 0),
QT_MOC_LITERAL(55, 581, 16, 0),
QT_MOC_LITERAL(56, 598, 13, 0),
QT_MOC_LITERAL(57, 612, 10, 0),
QT_MOC_LITERAL(58, 623, 10, 0),
QT_MOC_LITERAL(59, 634, 7, 0),
QT_MOC_LITERAL(60, 642, 8, 0),
QT_MOC_LITERAL(61, 651, 5, 0),
QT_MOC_LITERAL(62, 657, 10, 0),
QT_MOC_LITERAL(63, 668, 7, 0),
QT_MOC_LITERAL(64, 676, 10, 0),
QT_MOC_LITERAL(65, 687, 7, 0),
QT_MOC_LITERAL(66, 695, 12, 0),
QT_MOC_LITERAL(67, 708, 9, 0),
QT_MOC_LITERAL(68, 718, 5, 0),
QT_MOC_LITERAL(69, 724, 2, 0),
QT_MOC_LITERAL(70, 727, 5, 0),
QT_MOC_LITERAL(71, 733, 2, 0),
QT_MOC_LITERAL(72, 736, 5, 0),
QT_MOC_LITERAL(73, 742, 2, 0),
QT_MOC_LITERAL(74, 745, 5, 0),
QT_MOC_LITERAL(75, 751, 2, 0),
QT_MOC_LITERAL(76, 754, 5, 0),
QT_MOC_LITERAL(77, 760, 2, 0),
QT_MOC_LITERAL(78, 763, 5, 0),
QT_MOC_LITERAL(79, 769, 2, 0),
QT_MOC_LITERAL(80, 772, 5, 0),
QT_MOC_LITERAL(81, 778, 2, 0),
QT_MOC_LITERAL(82, 781, 5, 0),
QT_MOC_LITERAL(83, 787, 2, 0),
QT_MOC_LITERAL(84, 790, 5, 0),
QT_MOC_LITERAL(85, 796, 2, 0),
QT_MOC_LITERAL(86, 799, 5, 0),
QT_MOC_LITERAL(87, 805, 2, 0),
QT_MOC_LITERAL(88, 808, 9, 0),
QT_MOC_LITERAL(89, 818, 6, 0),
QT_MOC_LITERAL(90, 825, 8, 0),
QT_MOC_LITERAL(91, 834, 5, 0),
QT_MOC_LITERAL(92, 840, 9, 0),
QT_MOC_LITERAL(93, 850, 6, 0),
QT_MOC_LITERAL(94, 857, 17, 0),
QT_MOC_LITERAL(95, 875, 14, 0),
QT_MOC_LITERAL(96, 890, 14, 0),
QT_MOC_LITERAL(97, 905, 11, 0),
QT_MOC_LITERAL(98, 917, 16, 0),
QT_MOC_LITERAL(99, 934, 13, 0),
QT_MOC_LITERAL(100, 948, 9, 0),
QT_MOC_LITERAL(101, 958, 10, 0),
QT_MOC_LITERAL(102, 969, 7, 0),
QT_MOC_LITERAL(103, 977, 8, 0),
QT_MOC_LITERAL(104, 986, 5, 0),
QT_MOC_LITERAL(105, 992, 9, 0),
QT_MOC_LITERAL(106, 1002, 6, 0),
QT_MOC_LITERAL(107, 1009, 6, 0),
QT_MOC_LITERAL(108, 1016, 7, 0),
QT_MOC_LITERAL(109, 1024, 10, 0),
QT_MOC_LITERAL(110, 1035, 17, 0),
QT_MOC_LITERAL(111, 1053, 12, 0),
QT_MOC_LITERAL(112, 1066, 8, 0),
QT_MOC_LITERAL(113, 1075, 7, 0),
QT_MOC_LITERAL(114, 1083, 8, 0)
    },
    "VISM::_DVisM\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0"
    "argc\0argv\0AboutBox\0Connect\0ConnectionString\0Tag\0DeleteConnection\0Execute\0"
    "Code\0GetConnStr\0inConnStr\0LoadGblFromFile\0FileName\0LoadRtnFromFile\0Format\0"
    "SetBatchMode\0BatchMode\0SetCode\0SetConnTag\0ConnTag\0SetConnectionState\0"
    "ConnectionState\0SetControlClasses\0ControlClasses\0SetElapsedTime\0ElapsedTime\0"
    "SetError\0Error\0SetErrorName\0ErrorName\0SetErrorTrap\0ErrorTrap\0SetExecFlag\0"
    "ExecFlag\0SetForm\0Form\0SetFormName\0FormName\0SetINTCode\0INTCode\0SetInterval\0"
    "Interval\0SetKeepAliveInterval\0KeepAliveInterval\0SetKeepAliveTimeout\0"
    "KeepAliveTimeout\0SetLoadOption\0LoadOption\0SetLogMask\0LogMask\0SetMCode\0MCode\0"
    "SetMServer\0MServer\0SetMsgText\0MsgText\0SetNameSpace\0NameSpace\0SetP0\0P0\0SetP1\0"
    "P1\0SetP2\0P2\0SetP3\0P3\0SetP4\0P4\0SetP5\0P5\0SetP6\0P6\0SetP7\0P7\0SetP8\0P8\0SetP9\0P9\0"
    "SetPDELIM\0PDELIM\0SetPLIST\0PLIST\0SetPrefix\0Prefix\0SetPromptInterval\0PromptInterval\0"
    "SetRoutineName\0RoutineName\0SetRoutineSource\0RoutineSource\0SetServer\0SetTimeOut\0"
    "TimeOut\0SetVALUE\0VALUE\0set_VALUE\0_VALUE\0Server\0control\0VISM::VisM\0Event Interface 1\0"
    "_DVisMEvents\0Executed\0OnError\0ShutDown\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VISM___DVisM[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    54, 14, // methods
    43, 458, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 284, 2, 5,
    7, 1, 293, 2, 5,
    9, 3, 296, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 303, 2, 9,
    13, 1, 304, 2, 11,
    13, 2, 307, 2, 9,
    16, 0, 312, 2, 9,
    17, 1, 313, 2, 9,
    19, 1, 316, 2, 9,
    21, 1, 319, 2, 9,
    23, 2, 322, 2, 9,
    25, 1, 327, 2, 9,
    27, 1, 330, 2, 9,
    28, 1, 333, 2, 9,
    30, 1, 336, 2, 9,
    32, 1, 339, 2, 9,
    34, 1, 342, 2, 9,
    36, 1, 345, 2, 9,
    38, 1, 348, 2, 9,
    40, 1, 351, 2, 9,
    42, 1, 354, 2, 9,
    44, 1, 357, 2, 9,
    46, 1, 360, 2, 9,
    48, 1, 363, 2, 9,
    50, 1, 366, 2, 9,
    52, 1, 369, 2, 9,
    54, 1, 372, 2, 9,
    56, 1, 375, 2, 9,
    58, 1, 378, 2, 9,
    60, 1, 381, 2, 9,
    62, 1, 384, 2, 9,
    64, 1, 387, 2, 9,
    66, 1, 390, 2, 9,
    68, 1, 393, 2, 9,
    70, 1, 396, 2, 9,
    72, 1, 399, 2, 9,
    74, 1, 402, 2, 9,
    76, 1, 405, 2, 9,
    78, 1, 408, 2, 9,
    80, 1, 411, 2, 9,
    82, 1, 414, 2, 9,
    84, 1, 417, 2, 9,
    86, 1, 420, 2, 9,
    88, 1, 423, 2, 9,
    90, 1, 426, 2, 9,
    92, 1, 429, 2, 9,
    94, 1, 432, 2, 9,
    96, 1, 435, 2, 9,
    98, 1, 438, 2, 9,
    100, 1, 441, 2, 11,
    100, 2, 444, 2, 9,
    101, 1, 449, 2, 9,
    103, 1, 452, 2, 9,
    105, 1, 455, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QVariant, 14, 15,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::QString, QMetaType::QString, 20,
    QMetaType::Bool, QMetaType::QString, 22,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, 22, 24,
    QMetaType::Void, QMetaType::Int, 26,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, 29,
    QMetaType::Void, QMetaType::Int, 31,
    QMetaType::Void, QMetaType::QString, 33,
    QMetaType::Void, QMetaType::Int, 35,
    QMetaType::Void, QMetaType::Int, 37,
    QMetaType::Void, QMetaType::QString, 39,
    QMetaType::Void, QMetaType::Bool, 41,
    QMetaType::Void, QMetaType::Int, 43,
    QMetaType::Void, QMetaType::QString, 45,
    QMetaType::Void, QMetaType::QString, 47,
    QMetaType::Void, QMetaType::QString, 49,
    QMetaType::Void, QMetaType::Int, 51,
    QMetaType::Void, QMetaType::Int, 53,
    QMetaType::Void, QMetaType::Int, 55,
    QMetaType::Void, QMetaType::Int, 57,
    QMetaType::Void, QMetaType::Int, 59,
    QMetaType::Void, QMetaType::QString, 61,
    QMetaType::Void, QMetaType::QString, 63,
    QMetaType::Void, QMetaType::QString, 65,
    QMetaType::Void, QMetaType::QString, 67,
    QMetaType::Void, QMetaType::QVariant, 69,
    QMetaType::Void, QMetaType::QVariant, 71,
    QMetaType::Void, QMetaType::QVariant, 73,
    QMetaType::Void, QMetaType::QVariant, 75,
    QMetaType::Void, QMetaType::QVariant, 77,
    QMetaType::Void, QMetaType::QVariant, 79,
    QMetaType::Void, QMetaType::QVariant, 81,
    QMetaType::Void, QMetaType::QVariant, 83,
    QMetaType::Void, QMetaType::QVariant, 85,
    QMetaType::Void, QMetaType::QVariant, 87,
    QMetaType::Void, QMetaType::QVariant, 89,
    QMetaType::Void, QMetaType::QVariant, 91,
    QMetaType::Void, QMetaType::QString, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::QString, 97,
    QMetaType::Void, QMetaType::QString, 99,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QVariant, 14, 15,
    QMetaType::Void, QMetaType::Int, 102,
    QMetaType::Void, QMetaType::QVariant, 104,
    QMetaType::Void, QMetaType::QVariant, 106,

 // properties: name, type, flags
    26, QMetaType::Int, 0x02015003, 		 // int BatchMode
    18, QMetaType::QString, 0x0a015003, 		 // QString Code
    29, QMetaType::QString, 0x0a015003, 		 // QString ConnTag
    31, QMetaType::Int, 0x02015003, 		 // int ConnectionState
    33, QMetaType::QString, 0x0a015003, 		 // QString ControlClasses
    35, QMetaType::Int, 0x02015003, 		 // int ElapsedTime
    37, QMetaType::Int, 0x02015003, 		 // int Error
    39, QMetaType::QString, 0x0a015003, 		 // QString ErrorName
    41, QMetaType::Bool, 0x01015003, 		 // bool ErrorTrap
    43, QMetaType::Int, 0x02015003, 		 // int ExecFlag
    45, QMetaType::QString, 0x0a015003, 		 // QString Form
    47, QMetaType::QString, 0x0a015003, 		 // QString FormName
    49, QMetaType::QString, 0x0a015003, 		 // QString INTCode
    51, QMetaType::Int, 0x02015003, 		 // int Interval
    53, QMetaType::Int, 0x02015003, 		 // int KeepAliveInterval
    55, QMetaType::Int, 0x02015003, 		 // int KeepAliveTimeout
    57, QMetaType::Int, 0x02015003, 		 // int LoadOption
    59, QMetaType::Int, 0x02015003, 		 // int LogMask
    61, QMetaType::QString, 0x0a015003, 		 // QString MCode
    63, QMetaType::QString, 0x0a015003, 		 // QString MServer
    65, QMetaType::QString, 0x0a015003, 		 // QString MsgText
    67, QMetaType::QString, 0x0a015003, 		 // QString NameSpace
    69, QMetaType::QVariant, 0x29015003, 		 // QVariant P0
    71, QMetaType::QVariant, 0x29015003, 		 // QVariant P1
    73, QMetaType::QVariant, 0x29015003, 		 // QVariant P2
    75, QMetaType::QVariant, 0x29015003, 		 // QVariant P3
    77, QMetaType::QVariant, 0x29015003, 		 // QVariant P4
    79, QMetaType::QVariant, 0x29015003, 		 // QVariant P5
    81, QMetaType::QVariant, 0x29015003, 		 // QVariant P6
    83, QMetaType::QVariant, 0x29015003, 		 // QVariant P7
    85, QMetaType::QVariant, 0x29015003, 		 // QVariant P8
    87, QMetaType::QVariant, 0x29015003, 		 // QVariant P9
    89, QMetaType::QVariant, 0x29015003, 		 // QVariant PDELIM
    91, QMetaType::QVariant, 0x29015003, 		 // QVariant PLIST
    93, QMetaType::QString, 0x0a015003, 		 // QString Prefix
    95, QMetaType::Int, 0x02015003, 		 // int PromptInterval
    97, QMetaType::QString, 0x0a015003, 		 // QString RoutineName
    99, QMetaType::QString, 0x0a015003, 		 // QString RoutineSource
    107, QMetaType::QString, 0x0a015003, 		 // QString Server
    102, QMetaType::Int, 0x02015003, 		 // int TimeOut
    104, QMetaType::QVariant, 0x29015003, 		 // QVariant VALUE
    106, QMetaType::QVariant, 0x29015003, 		 // QVariant _VALUE
    108, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _DVisM::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VISM___DVisM, 0, 0, 0 }
};

void *_DVisM::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VISM::_DVisM"))
        return static_cast<void*>(const_cast<_DVisM*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_VISM__VisM[] = {

 // content:
    7, // revision
    109,  // classname
    1, 14, // classinfo
    57, 16, // methods
    42, 480, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    6, // signal count

 // classinfo: key, value
    110, 111, 

// signal: name, argc, parameters, tag, flags
    112, 0, 301, 2, 5,
    113, 0, 302, 2, 5,
    114, 1, 303, 2, 5,
    1, 4, 306, 2, 5,
    7, 1, 315, 2, 5,
    9, 3, 318, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 325, 2, 9,
    13, 1, 326, 2, 11,
    13, 2, 329, 2, 9,
    16, 0, 334, 2, 9,
    17, 1, 335, 2, 9,
    19, 1, 338, 2, 9,
    21, 1, 341, 2, 9,
    23, 2, 344, 2, 9,
    25, 1, 349, 2, 9,
    27, 1, 352, 2, 9,
    28, 1, 355, 2, 9,
    30, 1, 358, 2, 9,
    32, 1, 361, 2, 9,
    34, 1, 364, 2, 9,
    36, 1, 367, 2, 9,
    38, 1, 370, 2, 9,
    40, 1, 373, 2, 9,
    42, 1, 376, 2, 9,
    44, 1, 379, 2, 9,
    46, 1, 382, 2, 9,
    48, 1, 385, 2, 9,
    50, 1, 388, 2, 9,
    52, 1, 391, 2, 9,
    54, 1, 394, 2, 9,
    56, 1, 397, 2, 9,
    58, 1, 400, 2, 9,
    60, 1, 403, 2, 9,
    62, 1, 406, 2, 9,
    64, 1, 409, 2, 9,
    66, 1, 412, 2, 9,
    68, 1, 415, 2, 9,
    70, 1, 418, 2, 9,
    72, 1, 421, 2, 9,
    74, 1, 424, 2, 9,
    76, 1, 427, 2, 9,
    78, 1, 430, 2, 9,
    80, 1, 433, 2, 9,
    82, 1, 436, 2, 9,
    84, 1, 439, 2, 9,
    86, 1, 442, 2, 9,
    88, 1, 445, 2, 9,
    90, 1, 448, 2, 9,
    92, 1, 451, 2, 9,
    94, 1, 454, 2, 9,
    96, 1, 457, 2, 9,
    98, 1, 460, 2, 9,
    100, 1, 463, 2, 11,
    100, 2, 466, 2, 9,
    101, 1, 471, 2, 9,
    103, 1, 474, 2, 9,
    105, 1, 477, 2, 9,

// signal: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 31,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QVariant, 14, 15,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::QString, QMetaType::QString, 20,
    QMetaType::Bool, QMetaType::QString, 22,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, 22, 24,
    QMetaType::Void, QMetaType::Int, 26,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, 29,
    QMetaType::Void, QMetaType::Int, 31,
    QMetaType::Void, QMetaType::QString, 33,
    QMetaType::Void, QMetaType::Int, 35,
    QMetaType::Void, QMetaType::Int, 37,
    QMetaType::Void, QMetaType::QString, 39,
    QMetaType::Void, QMetaType::Bool, 41,
    QMetaType::Void, QMetaType::Int, 43,
    QMetaType::Void, QMetaType::QString, 45,
    QMetaType::Void, QMetaType::QString, 47,
    QMetaType::Void, QMetaType::QString, 49,
    QMetaType::Void, QMetaType::Int, 51,
    QMetaType::Void, QMetaType::Int, 53,
    QMetaType::Void, QMetaType::Int, 55,
    QMetaType::Void, QMetaType::Int, 57,
    QMetaType::Void, QMetaType::Int, 59,
    QMetaType::Void, QMetaType::QString, 61,
    QMetaType::Void, QMetaType::QString, 63,
    QMetaType::Void, QMetaType::QString, 65,
    QMetaType::Void, QMetaType::QString, 67,
    QMetaType::Void, QMetaType::QVariant, 69,
    QMetaType::Void, QMetaType::QVariant, 71,
    QMetaType::Void, QMetaType::QVariant, 73,
    QMetaType::Void, QMetaType::QVariant, 75,
    QMetaType::Void, QMetaType::QVariant, 77,
    QMetaType::Void, QMetaType::QVariant, 79,
    QMetaType::Void, QMetaType::QVariant, 81,
    QMetaType::Void, QMetaType::QVariant, 83,
    QMetaType::Void, QMetaType::QVariant, 85,
    QMetaType::Void, QMetaType::QVariant, 87,
    QMetaType::Void, QMetaType::QVariant, 89,
    QMetaType::Void, QMetaType::QVariant, 91,
    QMetaType::Void, QMetaType::QString, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::QString, 97,
    QMetaType::Void, QMetaType::QString, 99,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QVariant, 14, 15,
    QMetaType::Void, QMetaType::Int, 102,
    QMetaType::Void, QMetaType::QVariant, 104,
    QMetaType::Void, QMetaType::QVariant, 106,

 // properties: name, type, flags
    26, QMetaType::Int, 0x02015003, 		 // int BatchMode
    18, QMetaType::QString, 0x0a015003, 		 // QString Code
    29, QMetaType::QString, 0x0a015003, 		 // QString ConnTag
    31, QMetaType::Int, 0x02015003, 		 // int ConnectionState
    33, QMetaType::QString, 0x0a015003, 		 // QString ControlClasses
    35, QMetaType::Int, 0x02015003, 		 // int ElapsedTime
    37, QMetaType::Int, 0x02015003, 		 // int Error
    39, QMetaType::QString, 0x0a015003, 		 // QString ErrorName
    41, QMetaType::Bool, 0x01015003, 		 // bool ErrorTrap
    43, QMetaType::Int, 0x02015003, 		 // int ExecFlag
    45, QMetaType::QString, 0x0a015003, 		 // QString Form
    47, QMetaType::QString, 0x0a015003, 		 // QString FormName
    49, QMetaType::QString, 0x0a015003, 		 // QString INTCode
    51, QMetaType::Int, 0x02015003, 		 // int Interval
    53, QMetaType::Int, 0x02015003, 		 // int KeepAliveInterval
    55, QMetaType::Int, 0x02015003, 		 // int KeepAliveTimeout
    57, QMetaType::Int, 0x02015003, 		 // int LoadOption
    59, QMetaType::Int, 0x02015003, 		 // int LogMask
    61, QMetaType::QString, 0x0a015003, 		 // QString MCode
    63, QMetaType::QString, 0x0a015003, 		 // QString MServer
    65, QMetaType::QString, 0x0a015003, 		 // QString MsgText
    67, QMetaType::QString, 0x0a015003, 		 // QString NameSpace
    69, QMetaType::QVariant, 0x29015003, 		 // QVariant P0
    71, QMetaType::QVariant, 0x29015003, 		 // QVariant P1
    73, QMetaType::QVariant, 0x29015003, 		 // QVariant P2
    75, QMetaType::QVariant, 0x29015003, 		 // QVariant P3
    77, QMetaType::QVariant, 0x29015003, 		 // QVariant P4
    79, QMetaType::QVariant, 0x29015003, 		 // QVariant P5
    81, QMetaType::QVariant, 0x29015003, 		 // QVariant P6
    83, QMetaType::QVariant, 0x29015003, 		 // QVariant P7
    85, QMetaType::QVariant, 0x29015003, 		 // QVariant P8
    87, QMetaType::QVariant, 0x29015003, 		 // QVariant P9
    89, QMetaType::QVariant, 0x29015003, 		 // QVariant PDELIM
    91, QMetaType::QVariant, 0x29015003, 		 // QVariant PLIST
    93, QMetaType::QString, 0x0a015003, 		 // QString Prefix
    95, QMetaType::Int, 0x02015003, 		 // int PromptInterval
    97, QMetaType::QString, 0x0a015003, 		 // QString RoutineName
    99, QMetaType::QString, 0x0a015003, 		 // QString RoutineSource
    107, QMetaType::QString, 0x0a015003, 		 // QString Server
    102, QMetaType::Int, 0x02015003, 		 // int TimeOut
    104, QMetaType::QVariant, 0x29015003, 		 // QVariant VALUE
    106, QMetaType::QVariant, 0x29015003, 		 // QVariant _VALUE

    0 // eod
};

const QMetaObject VisM::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VISM__VisM, 0, 0, 0 }
};

void *VisM::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VISM::VisM"))
        return static_cast<void*>(const_cast<VisM*>(this));
    return QAxWidget::qt_metacast(_clname);
}

